//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaTecnicaInnovationStrategiesv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroInfraccionesVehiculare
    {
        public int IdRegistroInfraccionesVehiculares { get; set; }
        public string Hora { get; set; }
        public string Fecha { get; set; }
        public string Conductor { get; set; }
        public string Vehiculo { get; set; }
        public string IdentificadorInfraccion { get; set; }
        public Nullable<int> PuntosConductorAntesInfraccion { get; set; }
        public Nullable<int> PuntosaDescontar { get; set; }
        public Nullable<int> PuntosConductorDespuesInfraccion { get; set; }
    }
}
